### ISSUE TITLE
Outlook grid: are there any examples or documentation of how to use it?

### ISSUE THREAD

**Issue by dquinter** [Wagnerp/Krypton-Toolkit-Suite-Extended-NET-5.470#106]
I'm lost and I don't know how to use this control

Thanks!

**Comment by Wagnerp** [comment]
Hi @dquinter 

Thanks for the question, yes there is documentation from the original developer https://www.jdhsoftware.com/products/krypton-outlookgrid/documentation/

**Comment by dquinter** [comment]
Thanks @Wagnerp!

**Comment by Wagnerp** [comment]
That's ok
