### ISSUE TITLE
Feature: OutlookGridGroup Backcolor property

### ISSUE THREAD

**Issue by richterAl** [Wagnerp/Krypton-Toolkit-Suite-Extended-NET-5.470#107]
Hello,

I would like to request a new feature for the OutlookGridGroup:
A **Backcolor** Property.

I have tried to implement such a feature. (see [https://github.com/richterAl/Krypton-Toolkit-Suite-Extended-NET-5.472/tree/feature/GroupBackColor](url))

But I think it is better to have the type PaletteBack instead of Color.
But I was not able to implement this property using this type.

**Comment by Wagnerp** [comment]
Transferred

**Comment by Wagnerp** [comment]
I think to use it `IPalette` needs to be used.

**Comment by Wagnerp** [comment]
https://wagnerp.github.io/Krypton-NET-5.470/Help/Output/api/ComponentFactory.Krypton.Toolkit.PaletteBack.html

**Comment by richterAl** [comment]
I solved my problem. 
I didn't recognize the SetInherit member of PaletteBack.
