### ISSUE TITLE
New messagebox icons

### ISSUE THREAD

**Issue by Wagnerp** [Wagnerp/Krypton-Toolkit-Suite-Extended-NET-5.470#12]
Possibly need to find new/suitable icons for messageboxes. CC license maybe?

**Comment by Smurf-IV** [comment]
https://www.1001freedownloads.com/free-icon/symbol-error

**Comment by Smurf-IV** [comment]
Each version of Visual studio comes with a separate _free re-useable_ downloadable icon / image pack.
The one with most images is the "VS2015 Image Library"

**Comment by Wagnerp** [comment]
Found it, good to know thanks.
