### ISSUE TITLE
A Krypton wizard control

### ISSUE THREAD

**Issue by Wagnerp** [Wagnerp/Krypton-Toolkit-Suite-Extended-NET-5.470#15]
This, but using Krypton controls

![image](https://user-images.githubusercontent.com/949607/36626857-33e462f0-1932-11e8-81a7-07fb9be341b7.png)

**Comment by Smurf-IV** [comment]
Needs the `CommandLink Button`

**Comment by Wagnerp** [comment]
Will work on it ASAP. Have also implemented new methods to elevate the running application into admin mode. May need to find a way to link this method to the new UAC controls.

**Comment by Smurf-IV** [comment]
https://marketplace.visualstudio.com/items?itemName=dahall.WindowsFormsWizardTemplates

**Comment by Wagnerp** [comment]
I've actually included it back in the February update

**Comment by Smurf-IV** [comment]
Just needs to be n the Market place then 👍

**Comment by Wagnerp** [comment]
Will put a link to it. I think that it was part of the extended renderer project
