### ISSUE TITLE
Can "We" have a slider ON/OFF control - with theming ?

### ISSUE THREAD

**Issue by Smurf-IV** [Wagnerp/Krypton-Toolkit-Suite-Extended-NET-5.470#22]
Like this:
https://stackoverflow.com/questions/8176212/create-animated-button

As per the 
https://visualstudioproductteam.gallerycdn.vsassets.io/extensions/visualstudioproductteam/productivitypowertools2012/11.0.60403.0/1482138274609/88411/1/ToolsOptionsSupport.png

And / Or

- https://www.codeproject.com/Articles/1029499/ToggleSwitch-Winforms-Control
- https://www.codeproject.com/Articles/1215232/WPF-ToggleSwitch-Control
- https://www.codeproject.com/Articles/233583/WPFSpark-of-n-ToggleSwitch

**Comment by Wagnerp** [comment]
Working on it now.
