### ISSUE TITLE
I was wondering if there is any documentation or tutorials on how to use this new Krypton framework

### ISSUE THREAD

**Issue by GeraldoJansen** [Wagnerp/Krypton-Toolkit-Suite-Extended-NET-5.470#36]
Good morning to all.

I tried to use this version of Krypton and could not compile the project because it contains some references failures and some files with extensions like .wxs, .wixproj, .aip, .aiproj. I was wondering if this version has tutorials, documentation on how to install and use, would they?

Taking the opportunity I was wondering if the Krypton Toolkit Suite Extended would continue with the release for use in commercial products?

Thank you so much for your time and for this very meaningful contribution. I'm a fan of yours and good job!

@Wagnerp @Smurf-IV

**Comment by Wagnerp** [comment]
Hi @GeraldoJansen,

Those extensions are used for packaging and distributing the binaries in an installable format for those who don't want to build from source. Just `unload` these projects if you need to build from source. The Krypton Toolkit Suite Extended projects uses the same BSD-3 Clause license that is used for the Krypton-NET-4.xx projects.

**Comment by GeraldoJansen** [comment]
Good morning, Mr. @Wagnerp .

From what I see is not ready a stable version of the extended krypton so I look forward to this work that I see that every day is better and feel the excitement in the work of art that are the codes.

Thank you very much for your time and thank you for this work of yours that helps so many and contribute so much to the knowledge of all.
Good work for you.

**Comment by Wagnerp** [comment]
Hi @GeraldoJansen 

The Extended Toolkit has a rolling release schedule, so it won't be as stable as the normal toolkit. Having said that, I aim to turn it into a NuGet package, now that I've solved the issues behind why it was not installing properly.

**Comment by GeraldoJansen** [comment]
Good morning, @Wagnerp .

What good news. Good work and thank you.

**Comment by Wagnerp** [comment]
Hi @GeraldoJansen 

Do you mean the normal toolkit or the extended toolkit? If so I plan to upload .NET versions 4.0 to 4.7.2 to NuGet. I don't plan to release version `5.480` to NuGet anytime soon, since the .NET framework, version 4.8 is still in the early beta stages.

**Comment by GeraldoJansen** [comment]
Good evening, Mr. @Wagnerp .

I'm working with .NET 4.5, so I wanted both krypton form classico and extended krypton with compiling projects with the .NET 4.5 framework.

Appreciate your attention.

**Comment by Wagnerp** [comment]
Hi @GeraldoJansen 

A NuGet package for the classic suite is now available for .NET 4.5. One for the extended toolkit will be made available sometime on Friday 5th October.

**Comment by GeraldoJansen** [comment]
Thank you very much @Wagnerp
