### ISSUE TITLE
Cannot use Nuget package, because it pulls in LinqBridge as well !

### ISSUE THREAD

**Issue by Smurf-IV** [Wagnerp/Krypton-Toolkit-Suite-Extended-NET-5.470#48]
Projects that use nuget do not want to know about this as they will be using .Net 4 onwards

Nuget linked projects get the following compilation errors:
![image](https://user-images.githubusercontent.com/2418812/52902833-521bdf00-320e-11e9-8755-266200da8e25.png)

LinqBridge is for .Net 2.0
![image](https://user-images.githubusercontent.com/2418812/52902791-a7a3bc00-320d-11e9-8e5e-64f3ba6b1e1f.png)

**Comment by Smurf-IV** [comment]
Dll list pulled in via extended toolkit is too big for tha actual useable components (i.e. just the Ext toolkit please!)
![image](https://user-images.githubusercontent.com/2418812/52902886-17ff0d00-320f-11e9-9526-01c72b558e2c.png)

**Comment by Wagnerp** [comment]
I'll remove the requirement in the March update. Just testing the toggle switch I've fixed that annoying flickering bug with it.
