### ISSUE TITLE
Help Needed: Krypton ListView

### ISSUE THREAD

**Issue by Wagnerp** [Wagnerp/Krypton-Toolkit-Suite-Extended-NET-5.470#51]
Help needed for development of (or fixing) the current Krypton list view component for upcoming additions.

**Comment by Smurf-IV** [comment]
What Appears to be the problem with it ? (Linked Items ?)
I have not had a specific problem. (But I do remember that assigning dataSource programmatically caused a problem in the past, not sure if I worked around it or not !)
