### ISSUE TITLE
In the updates of Readme, can you please put small picture examples

### ISSUE THREAD

**Issue by Smurf-IV** [Wagnerp/Krypton-Toolkit-Suite-Extended-NET-5.470#65]
Or even links to another page that allow a "browsing person" to follow and see what a "Picture wheel" looks like?

**Comment by Wagnerp** [comment]
Yes, sure, do you mean a screenshot of the example application?

**Comment by Smurf-IV** [comment]
I think each control as you complete it (Or when it has usable functionality)  should be enough.

**Comment by Wagnerp** [comment]
Now live
