### ISSUE TITLE
Palette Editor does not end when the application is closed

### ISSUE THREAD

**Issue by Smurf-IV** [Wagnerp/Krypton-Toolkit-Suite-Extended-NET-5.470#66]
Dangling unnamed worker thread prevents application from exiting the Task manager.

![image](https://user-images.githubusercontent.com/2418812/56846993-b83b7700-68cd-11e9-8211-983eb8b3654d.png)

**Comment by Wagnerp** [comment]
The `Palette Editor` is going to be replaced with the `Palette Explorer` app
