### ISSUE TITLE
The Following resource does not seem to exist in FlatTabControl

### ISSUE THREAD

**Issue by Smurf-IV** [Wagnerp/Krypton-Toolkit-Suite-Extended-NET-5.470#68]
Bitmap updownImage = ((System.Drawing.Bitmap)(resources.GetObject(**"TabIcons.bmp"**)));
Bitmap closeImage = ((System.Drawing.Bitmap)(resources.GetObject(**"CloseIcon.bmp"**)));

**Comment by Wagnerp** [comment]
Figured it out!
