### ISSUE TITLE
Playground test throws exception when selecting a theme

### ISSUE THREAD

**Issue by Smurf-IV** [Wagnerp/Krypton-Toolkit-Suite-Extended-NET-5.470#71]
- Start
- 1st "Test Bench"
- ListView
- Combo DropDown
- Select Office 2007-Black

Boom :

![image](https://user-images.githubusercontent.com/2418812/56847477-3bab9700-68d3-11e9-9fc4-59639f8594ae.png)

**Comment by Wagnerp** [comment]
Hi @Smurf-IV 

I think this has been fixed in the `Development` branch to use the newly created `ThemeManager`
