### ISSUE TITLE
How many MessageBoxes are being exported!?! and which work?

### ISSUE THREAD

**Issue by Smurf-IV** [Wagnerp/Krypton-Toolkit-Suite-Extended-NET-5.470#79]
I think I count at least 3 different versions of messegebox being exported, which work ?

Also, on this note, the DLL seems to have a lot of Test, and part filled in features, Please only have completed Items, and then have their names in the example images.

**Comment by Wagnerp** [comment]
The `ExtendedKryptonMessageBox` is the one that I'm using, I know that one of them was a a test to see if I could make a `Do Not Show Again` option, but can't quite get the font and alignment to work. Is the `Test` referring back to the `ExtraText` I've put in, i.e `MONTHNAME Update - Build: xxx`? If so, I've consolidated all the settings into one DLL, but that won't be rolled out fully until July. All the code is there and working, but it's the tedious task of ripping out all the old code and replacing it with the new code.

**Comment by Smurf-IV** [comment]
There is also (From memory - not at dev machine) one called `ExtendedKryptonMessageBoxOld` and `KryptonMessageBoxExtended`

The other sentence is about lot's f other things in the dll that do not seem to make sense (Again not at dev machine to remember names!)

**Comment by Wagnerp** [comment]
I'll take out `ExtendedKryptonMessageBoxOld` as it's not needed and the `KryptonMessageBoxExtended` is the one with the `Do Not Show Again` option in it.

**Comment by Wagnerp** [comment]
I've taken out `ExtendedKryptonMessageBoxOld` in the latest commit. Probably will remove `Extended File Dialogs.dll` in the June release, as that needs work to be done.

**Comment by Smurf-IV** [comment]
![image](https://user-images.githubusercontent.com/2418812/59563142-f7648980-902d-11e9-9b09-8ce0d49b54cc.png)

![image](https://user-images.githubusercontent.com/2418812/59563148-06e3d280-902e-11e9-9b6e-84bb2c41249e.png)

**Comment by Wagnerp** [comment]
Removed `KryptonMessageBoxBase.cs`
