### ISSUE TITLE
Properties.Resources.Designer.CS Yellow ICON 

### ISSUE THREAD

**Issue by pc8181** [Wagnerp/Krypton-Toolkit-Suite-Extended-NET-5.470#84]
today i just install from nuget :
Install-Package KryptonExtendedToolkit5470 -Version 5.470.1030

after that i add tools item in toolbar from Packages folder.
i drag Ribbon and compile but failed with below error 

System.InvalidOperationException: 'An error occurred creating the form. See Exception.InnerException for details.  The error is: Could not load file or assembly 'Krypton Ribbon, Version=5.470.796.0, Culture=neutral, PublicKeyToken=a87e673e9ecb6e8e' or one of its dependencies. The system cannot find the file specified.'

and warning symbol in : Properties.Resources.Designer.CS

how to populate toolbox items after nuget installed... i already set "Automatically Populate Toolbox" = True.

**Comment by Wagnerp** [comment]
Hi @pc8181 

The toolbox should automatically populate when you install the NuGet package into your project. Is this not happening? From the error, it's trying to find the `Krypton Ribbon` DLL, can you confirm that all the standard toolkit binaries are all present?

**Comment by pc8181** [comment]
Hi Sir,
      Finally 2 or 3 items tried and get tools in toolbox but i can see in my references look like below
![image](https://user-images.githubusercontent.com/13380400/59818629-466a3180-9342-11e9-9b3a-77d0bad9e764.png)

otherwise working fine after 2 hours struggled.

**Comment by Wagnerp** [comment]
Hi @pc8181 

Were you upgrading from an older version? If so, I think I may have removed the errant `Properties.Resources.Designer.dll`.

**Comment by pc8181** [comment]
Hi Sir,
    No, i just fresh installation from Nuget ... today right now i create new project and try to install KryptonExtendedToolKit5470, i hv the same problem see the screentshot

![image](https://user-images.githubusercontent.com/13380400/59838796-33b92200-936d-11e9-929e-9abfafabfe59.png)

**Comment by Wagnerp** [comment]
Hi @pc8181 

What happens if you remove the reference for `Properties.Resources.Designer`?

**Comment by Wagnerp** [comment]
Hi @pc8181 

Are you still having the same issue?

**Comment by pc8181** [comment]
ooh Sorry for late ...
  after removed nothing happen working as fine sir.. but first time i saw a .cs file as a reference 

Thanks

**Comment by Wagnerp** [comment]
Is the issue resolved in 1180?
