### ISSUE TITLE
Can the "Extended Toolit" be broken into seperate "Chunks"...

### ISSUE THREAD

**Issue by Smurf-IV** [Wagnerp/Krypton-Toolkit-Suite-Extended-NET-5.470#87]
When downloading the existing "Extended kit" just to use a MessageBox and a button, It needs to pull in several Third Party NuGet  packages as well.

Please can these third party package requirements be "broken out" into seperate "singular" extensions, so that if a user want to use scintilla etc. they can take that nuget extension as needed.

**Comment by Wagnerp** [comment]
Do you mean like a core/basic and full versions? If so yes, that will be possible.

**Comment by Wagnerp** [comment]
I've actually thought about it when doing the floating tool/menu strips!

**Comment by Smurf-IV** [comment]
> Do you mean like a core/basic and full versions? If so yes, that will be possible.

Probably, 
_Core:_ Only a single dll that has the controls that do not need any other nuGet package (Apart from Krypton base !)
_Winform Anim Ext:_ The controls that allow animation (With Core as a dependency etc)
_Scintilla Ext:_ An Additional Ext Dll that overrides those controls (With Core as a dependency etc)
_APICodePack Ext:_ whatever is needed for that to happen until other methods that do not rely on them are used (With Core as a dependency etc)
_Experimental Ext:_ Controls that are still underdevelopment (Probably the equivalent of your Full version)

**Comment by Wagnerp** [comment]
Will need to pick apart the toolkit to see which controls go where. Might also do a colour control one and a dialogs one plus a IO/System one for file system controls.

**Comment by Wagnerp** [comment]
Hi @Smurf-IV 

I found out that **all** modules will require the standard toolkit as a base. By doing this, it makes me wonder if I should split up the standard toolkit into modular NuGet packages too?

**Comment by Smurf-IV** [comment]
> if I should split up the standard toolkit into modular NuGet packages too?

At least just the "base Component controls", and then leave the Complete Toolkit as the current "Standard" NuGet package.
Not Sure what it could be called (Minimal, Base, Controls, Toolkit Controls only, ... )

**Comment by Wagnerp** [comment]
Yes still have all binaries all in one package, but have 6 new packages for each separate DLL/XML files. I may also package all the palette XML files into another separate module package.

Maybe name them as follows:-

- Core - Contains just the `Toolkit` DLL
- Docking - Contains just the `Docking` DLL
- Navigator - Contains just the `Navigator` DLL
- Ribbon - Contains just the `Ribbon` DLL
- Workspace - Contains just the `Workspace` DLL

**Comment by Smurf-IV** [comment]
> Yes still have all binaries all in one package, but have 6 new packages for each separate DLL/XML files. I may also package all the palette XML files into another separate module package.

This will work, It will just be the "Management" of the NuGet releases thay could be the downfall of this.....
