### ISSUE TITLE
[Question] How to apply new font to all textboxes on my project?

### ISSUE THREAD

**Issue by dquinter** [Wagnerp/Krypton-Toolkit-Suite-Extended-NET-5.470#95]
Hi all.
I have a project with several textboxes, and I want everyone to have the same look & feel, and for that I want to apply a specific type of font.
How can I do it? One by one? Or can I create a new user control based on KryptonTextBox?
Thank you for any help you could give me.

**Comment by Wagnerp** [comment]
Hi @dquinter 

Just an update, the target release is for October. Completed the `StateCommon` focusing on the other 'States' now.

**Comment by Wagnerp** [comment]
Hi @dquinter & @Smurf-IV 

A package is now available to allow you to do this.
